Crash fix for enchanted hot item sockets
RootParent needs to be cached, it can change when accessed due to it being a computed property.
The crash in reference to this update was caused by the parent of the target item being validated as a Mobile, but then evaluating as a Corpse at a later point.

Exception:
System.InvalidCastException: Unable to cast object of type 'Server.Items.Corpse' to type 'Server.Mobile'.